### ISSUE TITLE
[Error and WARN] Server Fabric 1.20.1 + MVS 4.11

### ISSUE THREAD

**Issue by gkr0013** [FinnSetchell/MoogsVanillaStructuresV2#28]
Dear,

Small bug in the consol.

Server Fabric 1.20.1 (fabric-api-0.90.7+1.20.1.jar) with mvs-4.1.1-1.20-fabric.jar

[Server thread/ERROR]: Couldn't load structure mvs:houses/large_floating_island
net.minecraft.class_148: Loading NBT data
at net.minecraft.class_2487.method_10581(class_2487.java:506) ~[server-intermediary.jar:?]
at net.minecraft.class_2487$1.method_23240(class_2487.java:71) ~[server-intermediary.jar:?]
at net.minecraft.class_2487$1.method_23262(class_2487.java:57) ~[server-intermediary.jar:?]
at net.minecraft.class_2499$1.method_23249(class_2499.java:43) ~[server-intermediary.jar:?]
at net.minecraft.class_2499$1.method_23262(class_2499.java:26) ~[server-intermediary.jar:?]
at net.minecraft.class_2487.method_10581(class_2487.java:500) ~[server-intermediary.jar:?]
at net.minecraft.class_2487$1.method_23240(class_2487.java:71) ~[server-intermediary.jar:?]
at net.minecraft.class_2487$1.method_23262(class_2487.java:57) ~[server-intermediary.jar:?]
at net.minecraft.class_2507.method_10626(class_2507.java:147) ~[server-intermediary.jar:?]
at net.minecraft.class_2507.method_10625(class_2507.java:91) ~[server-intermediary.jar:?]
at net.minecraft.class_2507.method_10629(class_2507.java:36) ~[server-intermediary.jar:?]
at net.minecraft.class_3485.method_15090(class_3485.java:227) ~[server-intermediary.jar:?]
at net.minecraft.class_3485.method_44231(class_3485.java:217) ~[server-intermediary.jar:?]
at net.minecraft.class_3485.method_15088(class_3485.java:130) ~[server-intermediary.jar:?]
at net.minecraft.class_3485.method_44245(class_3485.java:108) ~[server-intermediary.jar:?]
at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1740) ~[?:?]
at net.minecraft.class_3485.method_15094(class_3485.java:98) ~[server-intermediary.jar:?]
at net.minecraft.class_3485.method_15091(class_3485.java:86) ~[server-intermediary.jar:?]
at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar:?]
at net.minecraft.class_3781.method_27233(class_3781.java:81) ~[server-intermediary.jar:?]
at net.minecraft.class_3781.method_16628(class_3781.java:115) ~[server-intermediary.jar:?]
at net.minecraft.class_3790.<init>(class_3790.java:58) ~[server-intermediary.jar:?]
at net.minecraft.class_6624.method_38711(class_6624.java:73) ~[server-intermediary.jar:?]
at net.minecraft.class_3449.method_41621(class_3449.java:67) ~[server-intermediary.jar:?]
at net.minecraft.class_2852.method_12392(class_2852.java:460) ~[server-intermediary.jar:?]
at net.minecraft.class_2852.method_12395(class_2852.java:204) ~[server-intermediary.jar:?]
at net.minecraft.class_3898.method_43375(class_3898.java:625) ~[server-intermediary.jar:?]
at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
at net.minecraft.class_3215$class_4212.method_18859(class_3215.java:564) ~[server-intermediary.jar:?]
at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
at net.minecraft.class_3215$class_4212.method_16075(class_3215.java:573) ~[server-intermediary.jar:?]
at net.minecraft.class_3215.method_19492(class_3215.java:282) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:770) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[server-intermediary.jar:?]
at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:742) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.util.zip.ZipException: Corrupt GZIP trailer
at java.util.zip.GZIPInputStream.readTrailer(GZIPInputStream.java:225) ~[?:?]
at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:119) ~[?:?]
at net.minecraft.class_6826.method_39780(class_6826.java:94) ~[server-intermediary.jar:?]
at net.minecraft.class_6826.read(class_6826.java:32) ~[server-intermediary.jar:?]
at java.io.DataInputStream.readInt(DataInputStream.java:384) ~[?:?]
at net.minecraft.class_2495$1.method_23246(class_2495.java:29) ~[server-intermediary.jar:?]
at net.minecraft.class_2495$1.method_23262(class_2495.java:20) ~[server-intermediary.jar:?]
at net.minecraft.class_2487.method_10581(class_2487.java:500) ~[server-intermediary.jar:?]

[Worker-Main-7/WARN]: Moog's Voyager Structures: Empty or nonexistent pool: mvs:farm/side_pool which is being called from mvs:other_decoration/wooden_wheat_farm

[Worker-Main-19/WARN]: Moog's Voyager Structures: Empty or nonexistent pool: mvs:farm/side_pool which is being called from mvs:nature/short_oak_pathway

[Worker-Main-32/WARN]: Moog's Voyager Structures: Empty or nonexistent pool: mvs:mine_with_campsite/side_pool which is being called from mvs:other_decoration/mine_with_campsite

[Worker-Main-36/ERROR]: Couldn't load structure mvs:houses/deepslate_house
net.minecraft.class_148: Loading NBT data
	at net.minecraft.class_2487.method_10581(class_2487.java:506) ~[server-intermediary.jar:?]
	at net.minecraft.class_2487$1.method_23240(class_2487.java:71) ~[server-intermediary.jar:?]
	at net.minecraft.class_2487$1.method_23262(class_2487.java:57) ~[server-intermediary.jar:?]
	at net.minecraft.class_2499$1.method_23249(class_2499.java:43) ~[server-intermediary.jar:?]
	at net.minecraft.class_2499$1.method_23262(class_2499.java:26) ~[server-intermediary.jar:?]
	at net.minecraft.class_2487.method_10581(class_2487.java:500) ~[server-intermediary.jar:?]
	at net.minecraft.class_2487$1.method_23240(class_2487.java:71) ~[server-intermediary.jar:?]
	at net.minecraft.class_2487$1.method_23262(class_2487.java:57) ~[server-intermediary.jar:?]
	at net.minecraft.class_2507.method_10626(class_2507.java:147) ~[server-intermediary.jar:?]
	at net.minecraft.class_2507.method_10625(class_2507.java:91) ~[server-intermediary.jar:?]
	at net.minecraft.class_2507.method_10629(class_2507.java:36) ~[server-intermediary.jar:?]
	at net.minecraft.class_3485.method_15090(class_3485.java:227) ~[server-intermediary.jar:?]
	at net.minecraft.class_3485.method_44231(class_3485.java:217) ~[server-intermediary.jar:?]
	at net.minecraft.class_3485.method_15088(class_3485.java:130) ~[server-intermediary.jar:?]
	at net.minecraft.class_3485.method_44245(class_3485.java:108) ~[server-intermediary.jar:?]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1740) ~[?:?]
	at net.minecraft.class_3485.method_15094(class_3485.java:98) ~[server-intermediary.jar:?]
	at net.minecraft.class_3485.method_15091(class_3485.java:86) ~[server-intermediary.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar:?]
	at net.minecraft.class_3781.method_27233(class_3781.java:81) ~[server-intermediary.jar:?]
	at net.minecraft.class_3781.method_16628(class_3781.java:115) ~[server-intermediary.jar:?]
	at com.finndog.mvs.world.structures.pieces.PieceLimitedJigsawManager.assembleJigsawStructure(PieceLimitedJigsawManager.java:106) ~[mvs-4.1.1-1.20-fabric.jar:?]
	at com.finndog.mvs.world.structures.GenericJigsawStructure.method_38676(GenericJigsawStructure.java:213) ~[mvs-4.1.1-1.20-fabric.jar:?]
	at net.minecraft.class_3195.method_47932(class_3195.java:199) ~[server-intermediary.jar:?]
	at net.minecraft.class_3195.method_41614(class_3195.java:125) ~[server-intermediary.jar:?]
	at net.minecraft.class_2794.method_41044(class_2794.java:513) ~[server-intermediary.jar:?]
	at net.minecraft.class_2794.method_41041(class_2794.java:466) ~[server-intermediary.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at net.minecraft.class_2794.method_16129(class_2794.java:448) ~[server-intermediary.jar:?]
	at net.minecraft.class_2806.method_39464(class_2806.java:54) ~[server-intermediary.jar:?]
	at net.minecraft.class_2806.method_12154(class_2806.java:252) ~[server-intermediary.jar:?]
	at net.minecraft.class_3898.method_17225(class_3898.java:684) ~[server-intermediary.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar:?]
	at net.minecraft.class_3898.method_17224(class_3898.java:673) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_3900.method_17634(class_3900.java:62) ~[server-intermediary.jar:?]
	at net.minecraft.class_3846.method_16907(class_3846.java:91) ~[server-intermediary.jar:?]
	at net.minecraft.class_3846.method_16900(class_3846.java:146) ~[server-intermediary.jar:?]
	at net.minecraft.class_3846.run(class_3846.java:102) ~[server-intermediary.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.io.IOException: Invalid tag id: 14
	at net.minecraft.class_4614$1.method_39878(class_4614.java:58) ~[server-intermediary.jar:?]
	at net.minecraft.class_4614$1.method_23264(class_4614.java:63) ~[server-intermediary.jar:?]
	at net.minecraft.class_4614$1.method_23262(class_4614.java:56) ~[server-intermediary.jar:?]
	at net.minecraft.class_2487.method_10581(class_2487.java:500) ~[server-intermediary.jar:?]
	... 45 more

[Worker-Main-7/WARN]: Moog's Voyager Structures: Empty or nonexistent pool: mvs:farm/side_pool which is being called from mvs:other_decoration/wheat_grain_bin

[09:01:34] [Worker-Main-21/WARN]: Moog's Voyager Structures: Empty or nonexistent pool: mvs:houses/small_igloo_2/side_pool which is being called from mvs:houses/medium_igloo_2

Thanks

**Comment by purejosh** [comment]
My server logs are spammed with this error constantly. I know 1.20.1 isn't the latest release, so if this is fixed in a new version, so be it. 
```
[08:17:00] [Worker-Main-50/WARN]: Moog's Voyager Structures: Empty or nonexistent pool: mvs:farm/side_pool which is being called from mvs:nature/short_oak_pathway
```

**Comment by HuaLun666** [comment]
My server is also experiencing the same problem.

**Comment by purejosh** [comment]
Adding to this: 
https://gist.github.com/purejosh/cce18db6050fa1fdcb77dae5ae8dcf7a

@FinnSetchell, please take a look at this. I believe you've got some values that are mapped, that don't exist. It's clogging up our server logs, and is frustrating.

**Comment by FinnSetchell** [comment]
The empty or non existent side pool warnings are from some un-used jigsaw blocks placed inside some structures. If you dont want the errors to appear I would reccomend using a mod like log begone to remove them. They will not affect your game at all.

**Comment by purejosh** [comment]
Or you could be proactive and remove them from your structure files.

**Comment by FinnSetchell** [comment]
I will do this eventually, just prioritising other issues first that affect the mods function :)

**Comment by purejosh** [comment]
Sounds good, thanks for confirming.
